
pekko {
  actor {
    provider = "local"

    serializers {
      jackson-json = "org.apache.pekko.serialization.jackson.JacksonJsonSerializer",
      jackson-cbor = "org.apache.pekko.serialization.jackson.JacksonCborSerializer",
    }
    serialization-bindings {
//      "info.a24731.syllabol.persistence.PersistenceSerialization" = jackson-json,
      "info.a24731.syllabol.persistence.PersistenceSerialization" = jackson-cbor,
    }
  }

  persistence {
    journal {
      plugin = "pekko.persistence.jdbc.journal"
    }
    snapshot-store {
      plugin = "pekko.persistence.jdbc.snapshot"
    }
  }
}


pekko.persistence.jdbc {
  journal {
    use-shared-db = "slick"
  }
  snapshot {
    use-shared-db = "slick"
  }
}

jdbc-journal {
  use-shared-db = "slick"
}

jdbc-snapshot-store {
  use-shared-db = "slick"
}

jdbc-durable-state-store {
  use-shared-db = "slick"
}

pekko-persistence-jdbc {
  shared-databases {
    slick {
      profile = "slick.jdbc.PostgresProfile$"
      db {
        host = "localhost"
        host = ${?DB_HOST}
        port = 5432
        port = ${?DB_PORT}
        dbName = "syllabol_db"
        dbName = ${?DB_NAME}
        url = "jdbc:postgresql://"${pekko-persistence-jdbc.shared-databases.slick.db.host}":"${pekko-persistence-jdbc.shared-databases.slick.db.port}"/"${pekko-persistence-jdbc.shared-databases.slick.db.dbName}
        user = "postgres"
        user = ${?DB_USER}
        password = "postgres_password"
        password = ${?DB_PASSWORD}
        driver = "org.postgresql.Driver"
        numThreads = 5
        maxConnections = 5
        minConnections = 1
      }
    }
  }
}
